version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookstore-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=members
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
    networks:
      - app-network

  db:
    image: postgres:13
    container_name: bookstore-db
    environment:
      - POSTGRES_DB=members
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge